/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-DoIWannaKnow.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-OneForTheRoad.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-Arabella.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-IWantItAll.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-WhyDoYouOnlyCallMeWhenYoureHigh.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-SnapOutOfIt.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-KneeSocks.mp3
/home/nikhil/Music/ArcticMonkeys/ArcticMonkeys-IWannaBeYours.mp3
/home/nikhil/Music/Beatles/Beatles-ADayInTheLife.mp3
/home/nikhil/Music/BlackSabbath/BlackSabbath-Paranoid.mp3
/home/nikhil/Music/BonJovi/BonJovi-LivinonaPrayer.mp3
/home/nikhil/Music/BonJovi/BonJovi-Runaway.mp3
/home/nikhil/Music/CameronLanders/CameronLanders-PeaceOfMind.mp3
/home/nikhil/Music/CarlyRaeJepson/CarlyRaeJepsen-RunAwayWithMe.mp3
/home/nikhil/Music/Coldplay/Coldplay-ASkyFullOfStars.mp3
/home/nikhil/Music/Coldplay/Coldplay-TheScientiest.mp3
/home/nikhil/Music/Coldplay/Coldplay-Clocks.mp3
/home/nikhil/Music/Coldplay/Coldplay-FixYou.mp3
/home/nikhil/Music/Tiësto/Tiësto-BeautifulThings.mp3
/home/nikhil/Music/Eminem/Eminem-Beautiful.mp3
/home/nikhil/Music/Eminem/Eminem-GutsOverFearft.Sia.mp3
/home/nikhil/Music/Eminem/Eminem-LoseYourself.mp3
/home/nikhil/Music/Eminem/Eminem-SingForTheMoment.mp3
/home/nikhil/Music/Eminem/Eminem-Survival.mp3
/home/nikhil/Music/Eminem/Eminem-TillICollapse.mp3
/home/nikhil/Music/FiveFingerDeathPunch/FiveFingerDeathPunch-GotYourSix.mp3
/home/nikhil/Music/FiveFingerDeathPunch/FiveFingerDeathPunch-JekyllandHyde.mp3
/home/nikhil/Music/FiveFingerDeathPunch/FiveFingerDeathPunch-MyNemesis.mp3
/home/nikhil/Music/FiveFingerDeathPunch/FiveFingerDeathPunch-YoureNotMyKind.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-NoOneWillKnow.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-CareerAdvice.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-LetYourHeartHoldFast.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-UpFromTheGround.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-ImWrong.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-MovieScreens.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-NewYorkLights.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-MyLoveIsWithYou.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-TheWreckingBall.mp3
/home/nikhil/Music/FortAtlantic/FortAtlantic-ThereIsLove.mp3
/home/nikhil/Music/FortMinor/FortMinor-RememberTheName.mp3
/home/nikhil/Music/GreenDay/GreenDay-BoulvardBrokenDreams.mp3
/home/nikhil/Music/Queens/Queens-BohemianRhapsody.mp3
/home/nikhil/Music/TheLumineers/TheLumineers-HoHey.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Radioactive.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Tiptoe.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--It'sTime.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Demons.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--OnTopoftheWorld.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Amsterdam.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--HearMeOut.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--EveryNight.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--BleedingOut.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Underdog.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--NothingLefttoSay_Rocks.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Cha-Ching(TillWeGrowOlder).mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--WorkingMan.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--MyFault.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--RoundandRound.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--TheRiver.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--America.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--Selene.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--CoverUp.mp3
/home/nikhil/Music/ImagineDragons/ImagineDragons-NightVisions/ImagineDragons--IDon'tMind.mp3
/home/nikhil/Music/IronMaiden/IronMaiden-TheTrooper.mp3
/home/nikhil/Music/IronMaiden/IronMaiden-FearOfTheDark.mp3
/home/nikhil/Music/IronMaiden/IronMaiden-HallowedBeThyName.mp3
/home/nikhil/Music/IronMaiden/IronMaiden-RunToTheHills.mp3
/home/nikhil/Music/Journey/Journey-DontStopBelievin.mp3
/home/nikhil/Music/KrisAllen/KrisAllen-LiveLikeWereDying.mp3
/home/nikhil/Music/LedZeppelin/LedZeppelin-StairwayToHeaven.mp3
/home/nikhil/Music/ToveLo/ToveLo-TalkingBody.mp3
/home/nikhil/Music/JasonDerulo/JasonDerulo-WantToWantMe.mp3
/home/nikhil/Music/MajorLazerAndDJSnake/MajorLazerAndDJSnake-LeanOn.mp3
/home/nikhil/Music/NickJonas/NickJonas-Chains.mp3
/home/nikhil/Music/AndyGrammer/AndyGrammer-HoneyImGood.mp3
/home/nikhil/Music/TaylorSwift/TaylorSwift-Style.mp3
/home/nikhil/Music/EdSheeran/EdSheeran-ThinkingOutLoud.mp3
/home/nikhil/Music/LittleBigTown/LittleBigTown-GirlCrush.mp3
/home/nikhil/Music/CornradSewell/ConradSewell-HoldMeUp.mp3
/home/nikhil/Music/Clarity/Clarity-Scarecrow.mp3
/home/nikhil/Music/Jidenna/Jidenna-ClassicMan(RomanGianarthur).mp3
/home/nikhil/Music/AllTimeLow/AllTimeLow-SomethingsGottaGive.mp3
/home/nikhil/Music/SmallPools/SmallPools-Dreaming.mp3
/home/nikhil/Music/NormanGreenbaum/NormanGreenbaum-SpiritInTheSky.mp3
/home/nikhil/Music/Oasis/Oasis-Wonderwall.mp3
/home/nikhil/Music/PaulEngemann/PaulEngemann-PushItToTheLimit.mp3
/home/nikhil/Music/PinkFloyd/PinkFloyd-WishYouWereHere.mp3
/home/nikhil/Music/PinkFloyd/PinkFloyd-AnotherBrickInTheWallPartIII.mp3
/home/nikhil/Music/PinkFloyd/PinkFloyd-ComfortablyNumb.mp3
/home/nikhil/Music/Survivor/Survivor-EyeOfTheTiger.mp3
/home/nikhil/Music/Animals/Animals-HouseOfTheRisingSun.mp3
/home/nikhil/Music/TheEagles/TheEagles-HotelCalifornia.mp3
/home/nikhil/Music/TheLumineers/TheLumineers-Flowersinyourhair.mp3
/home/nikhil/Music/TheLumineers/TheLumineers-Ophelia.mp3
/home/nikhil/Music/TheLumineers/TheLumineers-StubbornLove.mp3
/home/nikhil/Music/TheLumineers/TheLumineers-Submarines.mp3
/home/nikhil/Music/Tiësto/Tiësto-AdagioForStrings.mp3
/home/nikhil/Music/Tiësto/Tiësto-MaximalCrazy.mp3
/home/nikhil/Music/Tiësto/Tiësto-SuburbanTrain.mp3
/home/nikhil/Music/TwoStepsFromHell/TwoStepsFromHell-Archangel.mp3
/home/nikhil/Music/TwoStepsFromHell/TwoStepsFromHell-Blackheart.mp3
/home/nikhil/Music/TwoStepsFromHell/TwostepsfromHell-HeartofCourage.mp3
/home/nikhil/Music/TwoStepsFromHell/TwoStepsFromHell-ProtectorsoftheEarth.mp3
/home/nikhil/Music/TwoStepsFromHell/TwoStepsFromHell-DragonRider.mp3
/home/nikhil/Music/Vargverket/Vargverket-Tjörn(BjörnOlsson).mp3
/home/nikhil/Music/ZZTop/ZZTop-Legs.mp3
/home/nikhil/Music/ZZTop/ZZTop-SharpDressedMan.mp3
